[package]
name = "day10"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "day10"
path = "src/lib.rs"

[[bin]]
name = "day10"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.75"
ndarray = "0.15.6"
